# Generated by Django 4.2.6 on 2024-09-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TWIB1", "0011_alter_content_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("desc", models.TextField(default="..")),
                ("copright", models.CharField(max_length=1000)),
                ("title", models.TextField(max_length=1000)),
                ("logo", models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("maintitle", models.CharField(max_length=1000)),
            ],
        ),
    ]
